Repository 2025-Ureca-Snac/snac-server, pull requests merged in 2025-07, with the labels that each got.

#3 초기 설정
  .github/workflows/auto-merge.yml
  .github/workflows/gradle-build.yml
  .github/workflows/lint-and-build.yml
  CODEOWNERS
  PULL_REQUEST_TEMPLATE.md
  workflows/auto-merge.yml
  workflows/lint-and-build.yml
Labels: bug

#6 [chore] CI/CD 초기 세팅
  .github/workflows/deploy.yml
  src/main/java/com/ureca/snac/common/BaseCode.java
  src/main/java/com/ureca/snac/common/CommonController.java
  src/main/resources/application.yml
Labels: enhancement, build

#11 [feat] add Actuator for health check
  build.gradle
  settings.gradle
Labels: build

#13 [feat] create MemberRepository
  .gitignore
  src/main/java/com/ureca/snac/member/MemberRepository.java
Labels: enhancement

#12 [feat] 은행 CRUD API 구현
  build.gradle
  src/main/java/com/ureca/snac/common/BaseCode.java
  src/main/java/com/ureca/snac/common/advice/GlobalAdvice.java
  src/main/java/com/ureca/snac/common/exception/BusinessException.java
  src/main/java/com/ureca/snac/finance/controller/BankController.java
  src/main/java/com/ureca/snac/finance/controller/request/CreateBankRequest.java
  src/main/java/com/ureca/snac/finance/controller/request/UpdateBankRequest.java
  src/main/java/com/ureca/snac/finance/entity/Bank.java
  src/main/java/com/ureca/snac/finance/exception/BankNotFoundException.java
  src/main/java/com/ureca/snac/finance/repository/BankRepository.java
  src/main/java/com/ureca/snac/finance/service/BankService.java
  src/main/java/com/ureca/snac/finance/service/BankServiceImpl.java
  src/main/java/com/ureca/snac/finance/service/response/BankResponse.java
Labels: enhancement

#17 [feat] 은행 유효성 검증 처리 및 에러 응답 구조 개선
  src/main/java/com/ureca/snac/common/ApiResponse.java
  src/main/java/com/ureca/snac/common/BaseCode.java
  src/main/java/com/ureca/snac/common/advice/GlobalAdvice.java
  src/main/java/com/ureca/snac/common/advice/ValidationErrorResponse.java
  src/main/java/com/ureca/snac/common/advice/ValidationErrorResponseWrapper.java
  src/main/java/com/ureca/snac/finance/service/BankService.java
Labels: documentation, enhancement

#18 feat: AWS SNS를 이용한 인증번호 발송(SNS 연동) 기능 추가
  build.gradle
  src/main/java/com/ureca/snac/auth/config/SnsConfig.java
  src/main/java/com/ureca/snac/auth/controller/JoinController.java
  src/main/java/com/ureca/snac/auth/controller/SnsController.java
  src/main/java/com/ureca/snac/auth/dto/request/JoinRequest.java
  src/main/java/com/ureca/snac/auth/dto/request/PhoneRequest.java
  src/main/java/com/ureca/snac/auth/dto/response/VerificationCodeResponse.java
  src/main/java/com/ureca/snac/auth/exception/AuthExceptionHandler.java
  src/main/java/com/ureca/snac/auth/exception/SmsSendFailedException.java
  src/main/java/com/ureca/snac/auth/service/JoinService.java
  src/main/java/com/ureca/snac/auth/service/JoinServiceImpl.java
  src/main/java/com/ureca/snac/auth/service/SnsService.java
  src/main/java/com/ureca/snac/common/BaseCode.java
  src/main/resources/application.yml
Labels: enhancement

#19 [feat] 데이터 거래 세팅
  src/main/java/com/ureca/snac/common/BaseCode.java
  src/main/java/com/ureca/snac/trade/entity/CancelReason.java
  src/main/java/com/ureca/snac/trade/entity/Notification.java
  src/main/java/com/ureca/snac/trade/entity/NotificationType.java
  src/main/java/com/ureca/snac/trade/entity/PaymentType.java
  src/main/java/com/ureca/snac/trade/entity/Trade.java
  src/main/java/com/ureca/snac/trade/entity/TradeHistory.java
  src/main/java/com/ureca/snac/trade/entity/TradeHistoryType.java
  src/main/java/com/ureca/snac/trade/entity/TradeStatus.java
  src/main/java/com/ureca/snac/trade/entity/Wallet.java
  src/main/java/com/ureca/snac/trade/repository/NotificationRepository.java
  src/main/java/com/ureca/snac/trade/repository/TradeHistoryRepository.java
  src/main/java/com/ureca/snac/trade/repository/TradeRepository.java
  src/main/java/com/ureca/snac/trade/repository/WalletRepository.java
Labels: enhancement

#22 [feat] 스낵머니 충전 api
  src/main/java/com/ureca/snac/auth/exception/AuthExceptionHandler.java
  src/main/java/com/ureca/snac/auth/exception/BusinessException.java
  src/main/java/com/ureca/snac/auth/service/JoinService.java
  src/main/java/com/ureca/snac/common/BaseCode.java
  src/main/java/com/ureca/snac/money/controller/MoneyRechargeController.java
  src/main/java/com/ureca/snac/money/controller/MoneyRechargeSwagger.java
  src/main/java/com/ureca/snac/money/dto/request/MoneyRechargeRequest.java
  src/main/java/com/ureca/snac/money/dto/response/MoneyRechargeResponse.java
  src/main/java/com/ureca/snac/money/entity/MoneyRecharge.java
  src/main/java/com/ureca/snac/money/entity/RechargeStatus.java
  src/main/java/com/ureca/snac/money/exception/AlreadyProcessedOrderException.java
  src/main/java/com/ureca/snac/money/exception/AmountMismatchException.java
  src/main/java/com/ureca/snac/money/exception/MoneyExceptionHandler.java
  src/main/java/com/ureca/snac/money/exception/OrderNotFoundException.java
  src/main/java/com/ureca/snac/money/repository/MoneyRechargeRepository.java
  src/main/java/com/ureca/snac/money/service/MoneyService.java
  src/main/java/com/ureca/snac/money/service/MoneyServiceImpl.java
  src/main/java/com/ureca/snac/swagger/annotation/error/ErrorCode400.java
  src/main/java/com/ureca/snac/swagger/annotation/error/ErrorCode401.java
  src/main/java/com/ureca/snac/swagger/annotation/error/ErrorCode403.java
  src/main/java/com/ureca/snac/swagger/annotation/error/ErrorCode404.java
  src/main/java/com/ureca/snac/swagger/annotation/error/ErrorCode409.java
  src/main/java/com/ureca/snac/swagger/annotation/error/ErrorCode500.java
  src/main/java/com/ureca/snac/swagger/annotation/response/ApiCreatedResponse.java
  src/main/java/com/ureca/snac/swagger/annotation/response/ApiNoContentResponse.java
  src/main/java/com/ureca/snac/swagger/annotation/response/ApiRechargeSuccessResponse.java
  src/main/java/com/ureca/snac/swagger/annotation/response/ApiRedirectResponse.java
  src/main/java/com/ureca/snac/swagger/annotation/response/ApiSuccessResponse.java
  src/main/java/com/ureca/snac/swagger/api/AuthControllerSwagger.java
  src/main/java/com/ureca/snac/swagger/response/ApiCreatedResponse.java
  src/main/java/com/ureca/snac/swagger/response/ApiNoContentResponse.java
  src/main/java/com/ureca/snac/swagger/response/ApiSuccessResponse.java
  src/main/resources/application.yml
Labels: enhancement

#23 [fix] conflict sol
  src/main/java/com/ureca/snac/auth/dto/CustomUserDetails.java
  src/main/java/com/ureca/snac/auth/service/JoinServiceImpl.java
  src/main/java/com/ureca/snac/auth/service/ReissueServiceImpl.java
  src/main/java/com/ureca/snac/money/controller/MoneyRechargeController.java
  src/main/java/com/ureca/snac/money/controller/MoneyRechargeSwagger.java
Labels: bug, wontfix

#25 [hotfix] CORS 설정 단순화 및 OPTIONS 요청 허용
  src/main/java/com/ureca/snac/auth/config/CorsMvcConfig.java
  src/main/java/com/ureca/snac/auth/config/SecurityConfig.java
Labels: bug, invalid, hotfix

#27 [feat] 구매 및 판매글 가격 필터링 보완
  src/main/java/com/ureca/snac/board/controller/CardController.java
  src/main/java/com/ureca/snac/board/controller/CardControllerSwagger.java
  src/main/java/com/ureca/snac/board/entity/Card.java
  src/main/java/com/ureca/snac/board/repository/CardRepository.java
  src/main/java/com/ureca/snac/board/repository/CardRepositoryCustom.java
  src/main/java/com/ureca/snac/board/repository/CardRepositoryImpl.java
  src/main/java/com/ureca/snac/board/service/CardService.java
  src/main/java/com/ureca/snac/board/service/CardServiceImpl.java
Labels: bug, documentation, enhancement

#28 [feat] 문자 검증 로직 구현
  build.gradle
  src/main/java/com/ureca/snac/auth/controller/SnsController.java
  src/main/java/com/ureca/snac/auth/controller/TestController.java
  src/main/java/com/ureca/snac/auth/dto/request/VerificationRequest.java
  src/main/java/com/ureca/snac/auth/dto/response/VerificationCodeResponse.java
  src/main/java/com/ureca/snac/auth/exception/AuthExceptionHandler.java
  src/main/java/com/ureca/snac/auth/exception/VerificationFailedException.java
  src/main/java/com/ureca/snac/auth/service/ReissueServiceImpl.java
  src/main/java/com/ureca/snac/auth/service/SnsService.java
  src/main/java/com/ureca/snac/auth/service/SnsServiceImpl.java
  src/main/java/com/ureca/snac/common/BaseCode.java
  src/main/resources/application.yml
Labels: enhancement

#30 [feat] 로그아웃 및 블랙리스팅
  src/main/java/com/ureca/snac/auth/config/SecurityConfig.java
  src/main/java/com/ureca/snac/auth/jwt/CustomLogoutFilter.java
  src/main/java/com/ureca/snac/auth/repository/RefreshRepository.java
  src/main/java/com/ureca/snac/auth/service/ReissueServiceImpl.java
  src/main/java/com/ureca/snac/common/BaseCode.java
Labels: enhancement

#31 [feat] 지갑 구현
  src/main/java/com/ureca/snac/auth/service/JoinServiceImpl.java
  src/main/java/com/ureca/snac/common/BaseCode.java
  src/main/java/com/ureca/snac/member/event/MemberJoinEvent.java
  src/main/java/com/ureca/snac/money/dto/request/MoneyRechargeRequest.java
  src/main/java/com/ureca/snac/money/entity/MoneyRecharge.java
  src/main/java/com/ureca/snac/money/entity/PaymentCategory.java
  src/main/java/com/ureca/snac/money/service/MoneyServiceImpl.java
  src/main/java/com/ureca/snac/trade/entity/Wallet.java
  src/main/java/com/ureca/snac/trade/repository/WalletRepository.java
  src/main/java/com/ureca/snac/wallet/Repository/WalletRepository.java
  src/main/java/com/ureca/snac/wallet/entity/Wallet.java
  src/main/java/com/ureca/snac/wallet/exception/InsufficientBalanceException.java
  src/main/java/com/ureca/snac/wallet/exception/InvalidAMountException.java
  src/main/java/com/ureca/snac/wallet/exception/WalletAlreadyExistsException.java
  src/main/java/com/ureca/snac/wallet/exception/WalletExceptionHandler.java
  src/main/java/com/ureca/snac/wallet/exception/WalletNotFoundException.java
  src/main/java/com/ureca/snac/wallet/listener/WalletEventListener.java
  src/main/java/com/ureca/snac/wallet/service/WalletService.java
  src/main/java/com/ureca/snac/wallet/service/WalletServiceImpl.java
  src/test/java/com/ureca/snac/wallet/service/WalletServiceTest.java
Labels: enhancement

#32 fix: solve TransientPropertyValueException
  src/main/java/com/ureca/snac/money/controller/MoneyRechargeController.java
  src/main/java/com/ureca/snac/money/service/MoneyService.java
  src/main/java/com/ureca/snac/money/service/MoneyServiceImpl.java
Labels: refactor, hotfix

#34 [feat] 계좌 생성/조회/수정/삭제 기능 구현
  src/main/java/com/ureca/snac/common/BaseCode.java
  src/main/java/com/ureca/snac/finance/controller/AccountController.java
  src/main/java/com/ureca/snac/finance/controller/AccountControllerSwagger.java
  src/main/java/com/ureca/snac/finance/controller/BankController.java
  src/main/java/com/ureca/snac/finance/controller/BankControllerSwagger.java
  src/main/java/com/ureca/snac/finance/controller/request/CreateAccountRequest.java
  src/main/java/com/ureca/snac/finance/controller/request/UpdateAccountRequest.java
  src/main/java/com/ureca/snac/finance/entity/Account.java
  src/main/java/com/ureca/snac/finance/exception/AccountNotFoundException.java
  src/main/java/com/ureca/snac/finance/repository/AccountRepository.java
  src/main/java/com/ureca/snac/finance/service/AccountNumberConverter.java
  src/main/java/com/ureca/snac/finance/service/AccountService.java
  src/main/java/com/ureca/snac/finance/service/AccountServiceImpl.java
  src/main/java/com/ureca/snac/finance/service/response/AccountResponse.java
  src/main/resources/application.yml
Labels: enhancement

#35 [feat] 구매/판매 card를 통한 거래 신청(생성) 및 수락 기능 및 알림 생성 기능
  build.gradle
  src/main/java/com/ureca/snac/common/BaseCode.java
  src/main/java/com/ureca/snac/notification/config/RabbitMqConfig.java
  src/main/java/com/ureca/snac/notification/dto/NotificationMessage.java
  src/main/java/com/ureca/snac/notification/entity/Notification.java
  src/main/java/com/ureca/snac/notification/entity/NotificationType.java
  src/main/java/com/ureca/snac/notification/repository/NotificationRepository.java
  src/main/java/com/ureca/snac/notification/service/NotificationService.java
  src/main/java/com/ureca/snac/notification/service/NotificationServiceImpl.java
  src/main/java/com/ureca/snac/trade/controller/TradeController.java
  src/main/java/com/ureca/snac/trade/dto/AcceptTradeRequest.java
  src/main/java/com/ureca/snac/trade/dto/TradeRequest.java
  src/main/java/com/ureca/snac/trade/dto/TradeResponse.java
  src/main/java/com/ureca/snac/trade/entity/Trade.java
  src/main/java/com/ureca/snac/trade/exception/DuplicateTradeRequestException.java
  src/main/java/com/ureca/snac/trade/exception/TradeNotFoundException.java
  src/main/java/com/ureca/snac/trade/exception/TradePermissionDeniedException.java
  src/main/java/com/ureca/snac/trade/exception/TradeSelfRequestException.java
  src/main/java/com/ureca/snac/trade/repository/TradeRepository.java
  src/main/java/com/ureca/snac/trade/service/TradeService.java
  src/main/java/com/ureca/snac/trade/service/TradeServiceImpl.java
  src/main/resources/application.yml
Labels: enhancement

#38 [fix] RabbitMQ 설정 오류 수정
  src/main/resources/application.yml
Labels: bug, build

#39 [hotfix] RabbitMQ 접속 설정 수정
  src/main/resources/application.yml
Labels: bug, build, chore

#42 [feat] 특정 유저 대상 알림 전송 기능 구현
  build.gradle
  src/main/java/com/ureca/snac/auth/config/SecurityConfig.java
  src/main/java/com/ureca/snac/notification/config/RabbitMQConfig.java
  src/main/java/com/ureca/snac/notification/config/RabbitMqConfig.java
  src/main/java/com/ureca/snac/notification/config/WebConfigRabbitMQ.java
  src/main/java/com/ureca/snac/notification/dto/NotificationDTO.java
  src/main/java/com/ureca/snac/notification/dto/NotificationMessage.java
  src/main/java/com/ureca/snac/notification/entity/Notification.java
  src/main/java/com/ureca/snac/notification/entity/NotificationType.java
  src/main/java/com/ureca/snac/notification/listener/NotificationListener.java
  src/main/java/com/ureca/snac/notification/repository/NotificationRepository.java
  src/main/java/com/ureca/snac/notification/service/NotificationService.java
  src/main/java/com/ureca/snac/notification/service/NotificationServiceImpl.java
  src/main/java/com/ureca/snac/trade/controller/TradeController.java
  src/main/java/com/ureca/snac/trade/controller/request/AcceptTradeRequest.java
  src/main/java/com/ureca/snac/trade/controller/request/TradeRequest.java
  src/main/java/com/ureca/snac/trade/entity/TradeStatus.java
  src/main/java/com/ureca/snac/trade/service/TradeService.java
  src/main/java/com/ureca/snac/trade/service/TradeServiceImpl.java
  src/main/java/com/ureca/snac/trade/service/response/TradeResponse.java
Labels: enhancement, build

#44 [hotfix] payment_type 컬럼 제거
  src/main/java/com/ureca/snac/trade/entity/Trade.java
Labels: bug

#50 [feat] S3 기반 파일 첨부 세팅, 데이터 전송 확인용 이미지 첨부 및 조회
  build.gradle
  src/main/java/com/ureca/snac/common/BaseCode.java
  src/main/java/com/ureca/snac/common/s3/S3Path.java
  src/main/java/com/ureca/snac/common/s3/S3Uploader.java
  src/main/java/com/ureca/snac/config/S3Config.java
  src/main/java/com/ureca/snac/config/S3Properties.java
  src/main/java/com/ureca/snac/trade/controller/AttachmentController.java
  src/main/java/com/ureca/snac/trade/dto/AttachmentRequestDto.java
  src/main/java/com/ureca/snac/trade/dto/AttachmentResponseDto.java
  src/main/java/com/ureca/snac/trade/entity/Attachment.java
  src/main/java/com/ureca/snac/trade/exception/AttachmentAlreadyExistsException.java
  src/main/java/com/ureca/snac/trade/exception/AttachmentNotFoundException.java
  src/main/java/com/ureca/snac/trade/exception/AttachmentPermissionDenied.java
  src/main/java/com/ureca/snac/trade/repository/AttachmentRepository.java
  src/main/java/com/ureca/snac/trade/service/AttachmentService.java
  src/main/java/com/ureca/snac/trade/service/AttachmentServiceImpl.java
  src/main/resources/application.yml
  src/test/java/com/ureca/snac/PasswordEncoderTest.java
Labels: enhancement

#51 [feat] 거래 내역 조회 및 기본 거래 프로세스 개선
  src/main/java/com/ureca/snac/board/exception/CardInvalidStatusException.java
  src/main/java/com/ureca/snac/common/BaseCode.java
  src/main/java/com/ureca/snac/trade/controller/BasicTradeController.java
  src/main/java/com/ureca/snac/trade/entity/Trade.java
  src/main/java/com/ureca/snac/trade/repository/CustomTradeRepository.java
  src/main/java/com/ureca/snac/trade/repository/TradeRepository.java
  src/main/java/com/ureca/snac/trade/repository/TradeRepositoryImpl.java
  src/main/java/com/ureca/snac/trade/service/BasicTradeService.java
  src/main/java/com/ureca/snac/trade/service/BasicTradeServiceImpl.java
  src/main/java/com/ureca/snac/trade/service/response/ScrollTradeResponse.java
  src/main/java/com/ureca/snac/trade/service/response/TradeResponse.java
Labels: enhancement

#53 [docs] 리드미 수정
  README.md
Labels: documentation

#54 [feat] 진행 중 거래 건수 조회 기능 추가
  src/main/java/com/ureca/snac/board/service/response/CardResponse.java
  src/main/java/com/ureca/snac/common/BaseCode.java
  src/main/java/com/ureca/snac/trade/controller/BasicTradeController.java
  src/main/java/com/ureca/snac/trade/controller/BasicTradeControllerSwagger.java
  src/main/java/com/ureca/snac/trade/repository/TradeRepository.java
  src/main/java/com/ureca/snac/trade/service/BasicTradeService.java
  src/main/java/com/ureca/snac/trade/service/BasicTradeServiceImpl.java
  src/main/java/com/ureca/snac/trade/service/response/ProgressTradeCountResponse.java
Labels: enhancement

#55 [feat] 거래 데이터 전송 로직에 이미지 첨부 기능 연결
  src/main/java/com/ureca/snac/trade/controller/AttachmentController.java
  src/main/java/com/ureca/snac/trade/service/AttachmentService.java
  src/main/java/com/ureca/snac/trade/service/AttachmentServiceImpl.java
  src/main/java/com/ureca/snac/trade/service/BasicTradeServiceImpl.java
Labels: enhancement

#57 [feat] 카드 거래 상태별 거래 진행 차단 및 단계별 문자 알림 구현
  src/main/java/com/ureca/snac/auth/service/SnsService.java
  src/main/java/com/ureca/snac/auth/service/SnsServiceImpl.java
  src/main/java/com/ureca/snac/common/advice/GlobalAdvice.java
  src/main/java/com/ureca/snac/trade/controller/BasicTradeController.java
  src/main/java/com/ureca/snac/trade/controller/BasicTradeControllerSwagger.java
  src/main/java/com/ureca/snac/trade/controller/request/ClaimBuyRequest.java
  src/main/java/com/ureca/snac/trade/repository/TradeRepository.java
  src/main/java/com/ureca/snac/trade/service/BasicTradeService.java
  src/main/java/com/ureca/snac/trade/service/BasicTradeServiceImpl.java
  src/main/java/com/ureca/snac/trade/service/response/TradeResponse.java
Labels: enhancement

#58 [chore] 테스트 서버 CORS 문제 해결
  src/main/java/com/ureca/snac/auth/config/SecurityConfig.java
Labels: build, chore

#63 [feat, refactor] 자산 내역 api 연동
  src/main/java/com/ureca/snac/asset/entity/AssetHistory.java
  src/main/java/com/ureca/snac/asset/entity/SourceDomain.java
  src/main/java/com/ureca/snac/asset/event/AssetChangedEvent.java
  src/main/java/com/ureca/snac/asset/service/AssetChangedEventFactory.java
  src/main/java/com/ureca/snac/asset/service/AssetHistoryService.java
  src/main/java/com/ureca/snac/dev/service/DevToolServiceImpl.java
  src/main/java/com/ureca/snac/money/service/MoneyServiceImpl.java
  src/main/java/com/ureca/snac/payment/service/PaymentServiceImpl.java
  src/main/java/com/ureca/snac/trade/service/TradeInitiationServiceImpl.java
Labels: enhancement, refactor

#65 [feat] OAuth2.0을 통한 소셜 계정 연동 및 로그인 구현
  build.gradle
  src/main/java/com/ureca/snac/auth/config/EmailConfig.java
  src/main/java/com/ureca/snac/auth/config/SecurityConfig.java
  src/main/java/com/ureca/snac/auth/controller/SocialLoginController.java
  src/main/java/com/ureca/snac/auth/controller/SocialLoginControllerSwagger.java
  src/main/java/com/ureca/snac/auth/dto/CustomOAuth2User.java
  src/main/java/com/ureca/snac/auth/dto/request/JoinRequest.java
  src/main/java/com/ureca/snac/auth/dto/response/GoogleResponse.java
  src/main/java/com/ureca/snac/auth/dto/response/KakaoResponse.java
  src/main/java/com/ureca/snac/auth/dto/response/NaverResponse.java
  src/main/java/com/ureca/snac/auth/dto/response/OAuth2Response.java
  src/main/java/com/ureca/snac/auth/exception/SocialLoginException.java
  src/main/java/com/ureca/snac/auth/filter/JWTFilter.java
  src/main/java/com/ureca/snac/auth/filter/LoginFilter.java
  src/main/java/com/ureca/snac/auth/oauth2/CustomAuthorizationRequestResolver.java
  src/main/java/com/ureca/snac/auth/oauth2/CustomOAuth2FailHandler.java
  src/main/java/com/ureca/snac/auth/oauth2/CustomOAuth2SuccessHandler.java
  src/main/java/com/ureca/snac/auth/repository/AuthRepository.java
  src/main/java/com/ureca/snac/auth/service/CustomOAuth2UserService.java
  src/main/java/com/ureca/snac/auth/service/CustomUserDetailsService.java
  src/main/java/com/ureca/snac/auth/service/JoinServiceImpl.java
  src/main/java/com/ureca/snac/auth/service/ReissueServiceImpl.java
  src/main/java/com/ureca/snac/auth/service/SocialLoginService.java
  src/main/java/com/ureca/snac/auth/service/SocialLoginServiceImpl.java
  src/main/java/com/ureca/snac/auth/util/CookieUtil.java
  src/main/java/com/ureca/snac/auth/util/JWTUtil.java
  src/main/java/com/ureca/snac/common/BaseCode.java
  src/main/java/com/ureca/snac/member/Member.java
  src/main/resources/application.yml
Labels: bug, enhancement, refactor, chore

#71 [feat] 분산락 적용 및 카드 조회 조건 수정
  build.gradle
  src/main/java/com/ureca/snac/board/controller/CardControllerSwagger.java
  src/main/java/com/ureca/snac/board/repository/CardRepositoryImpl.java
  src/main/java/com/ureca/snac/common/RedisKeyConstants.java
  src/main/java/com/ureca/snac/config/RedissonConfig.java
  src/main/java/com/ureca/snac/trade/service/WebSocketTradeEventListener.java
Labels: enhancement, build

#73 [feat] 거래 플로우 알림 기능 구현
  src/main/java/com/ureca/snac/notification/listener/NotificationListener.java
  src/main/java/com/ureca/snac/notification/service/NotificationService.java
  src/main/java/com/ureca/snac/notification/service/NotificationServiceImpl.java
  src/main/java/com/ureca/snac/trade/controller/MatchingController.java
  src/main/java/com/ureca/snac/trade/controller/TradeController.java
  src/main/java/com/ureca/snac/trade/controller/request/BuyerFilterRequest.java
  src/main/java/com/ureca/snac/trade/controller/request/CreateRealTimeTradePaymentRequest.java
  src/main/java/com/ureca/snac/trade/controller/request/CreateRealTimeTradeRequest.java
  src/main/java/com/ureca/snac/trade/controller/request/TradeApproveRequest.java
  src/main/java/com/ureca/snac/trade/dto/TradeDto.java
  src/main/java/com/ureca/snac/trade/entity/Trade.java
  src/main/java/com/ureca/snac/trade/service/MatchingServiceFacade.java
  src/main/java/com/ureca/snac/trade/service/TradeInitiationServiceImpl.java
  src/main/java/com/ureca/snac/trade/service/TradeQueryServiceImpl.java
  src/main/java/com/ureca/snac/trade/service/TradeServiceImpl.java
  src/main/java/com/ureca/snac/trade/service/interfaces/TradeInitiationService.java
  src/main/java/com/ureca/snac/trade/service/interfaces/TradeProgressService.java
  src/main/java/com/ureca/snac/trade/service/interfaces/TradeQueryService.java
Labels: enhancement

#76 [refactor] 토스 페이먼츠 api 리팩토링
  src/main/java/com/ureca/snac/common/BaseCode.java
  src/main/java/com/ureca/snac/infra/PaymentGatewayAdapter.java
  src/main/java/com/ureca/snac/infra/TossPaymentsAdapter.java
  src/main/java/com/ureca/snac/infra/TossPaymentsClient.java
  src/main/java/com/ureca/snac/infra/TossPaymentsErrorHandler.java
  src/main/java/com/ureca/snac/infra/config/TossAuthInterceptor.java
  src/main/java/com/ureca/snac/infra/dto/response/TossCancelResponse.java
  src/main/java/com/ureca/snac/money/exception/AmountMismatchException.java
  src/main/java/com/ureca/snac/money/repository/MoneyRechargeRepository.java
  src/main/java/com/ureca/snac/money/service/MoneyDepositor.java
  src/main/java/com/ureca/snac/money/service/MoneyServiceImpl.java
  src/main/java/com/ureca/snac/payment/controller/PaymentController.java
  src/main/java/com/ureca/snac/payment/controller/PaymentSwagger.java
  src/main/java/com/ureca/snac/payment/dto/PaymentCancelResponse.java
  src/main/java/com/ureca/snac/payment/entity/Payment.java
  src/main/java/com/ureca/snac/payment/exception/AlreadyProcessedPaymentException.java
  src/main/java/com/ureca/snac/payment/exception/PaymentAlreadyProcessedPaymentException.java
  src/main/java/com/ureca/snac/payment/exception/PaymentAmountMismatchException.java
  src/main/java/com/ureca/snac/payment/mapper/PaymentCancelMapper.java
  src/main/java/com/ureca/snac/payment/repository/PaymentRepository.java
  src/main/java/com/ureca/snac/payment/service/PaymentInternalService.java
  src/main/java/com/ureca/snac/payment/service/PaymentService.java
  src/main/java/com/ureca/snac/payment/service/PaymentServiceImpl.java
Labels: enhancement, refactor

#79 [refactor] 단골 api 리팩토링
  src/main/java/com/ureca/snac/favorite/controller/FavoriteController.java
  src/main/java/com/ureca/snac/favorite/controller/FavoriteSwagger.java
  src/main/java/com/ureca/snac/favorite/dto/CursorResult.java
  src/main/java/com/ureca/snac/favorite/dto/FavoriteCursor.java
  src/main/java/com/ureca/snac/favorite/dto/FavoriteMemberDto.java
  src/main/java/com/ureca/snac/favorite/repository/FavoriteRepository.java
  src/main/java/com/ureca/snac/favorite/service/FavoriteService.java
  src/main/java/com/ureca/snac/favorite/service/FavoriteServiceImpl.java
Labels: enhancement, refactor

#80 hotfix: "https://www.snac-app.com" CORS 허용
  src/main/java/com/ureca/snac/auth/config/SecurityConfig.java
Labels: hotfix

#81 [feat] 실시간 매칭 거래 예외 처리
  src/main/java/com/ureca/snac/board/exception/NotRealTimeSellCardException.java
  src/main/java/com/ureca/snac/board/repository/CardRepository.java
  src/main/java/com/ureca/snac/board/service/CardService.java
  src/main/java/com/ureca/snac/board/service/CardServiceImpl.java
  src/main/java/com/ureca/snac/common/BaseCode.java
  src/main/java/com/ureca/snac/common/advice/WebSocketExceptionHandler.java
  src/main/java/com/ureca/snac/config/RabbitMQConfig.java
  src/main/java/com/ureca/snac/notification/listener/NotificationListener.java
  src/main/java/com/ureca/snac/trade/controller/MatchingController.java
  src/main/java/com/ureca/snac/trade/controller/MatchingControllerSwagger.java
  src/main/java/com/ureca/snac/trade/dto/SocketErrorDto.java
  src/main/java/com/ureca/snac/trade/entity/Trade.java
  src/main/java/com/ureca/snac/trade/service/BuyFilterServiceImpl.java
  src/main/java/com/ureca/snac/trade/service/MatchingServiceFacade.java
  src/main/java/com/ureca/snac/trade/service/TradeInitiationServiceImpl.java
  src/main/java/com/ureca/snac/trade/service/TradeProgressServiceImpl.java
  src/main/java/com/ureca/snac/trade/service/WebSocketTradeEventListener.java
  src/main/java/com/ureca/snac/trade/service/interfaces/BuyFilterService.java
Labels: enhancement

#82 refactor: 소셜 연동 중복 가입 못하게 리팩토링
  src/main/java/com/ureca/snac/auth/service/CustomOAuth2UserService.java
Labels: enhancement, refactor

#84 [feat] BUY_REQUEST 및 ACCEPTED 단계 취소 기능 구현
  src/main/java/com/ureca/snac/config/RabbitMQConfig.java
  src/main/java/com/ureca/snac/notification/listener/NotificationListener.java
  src/main/java/com/ureca/snac/notification/service/NotificationService.java
  src/main/java/com/ureca/snac/notification/service/NotificationServiceImpl.java
  src/main/java/com/ureca/snac/trade/controller/MatchingController.java
  src/main/java/com/ureca/snac/trade/controller/request/CancelBuyRequest.java
  src/main/java/com/ureca/snac/trade/controller/request/CancelRealTimeTradeRequest.java
  src/main/java/com/ureca/snac/trade/dto/CancelTradeDto.java
  src/main/java/com/ureca/snac/trade/entity/CancelReason.java
  src/main/java/com/ureca/snac/trade/entity/Trade.java
  src/main/java/com/ureca/snac/trade/repository/TradeRepository.java
  src/main/java/com/ureca/snac/trade/service/MatchingServiceFacade.java
  src/main/java/com/ureca/snac/trade/service/TradeInitiationServiceImpl.java
  src/main/java/com/ureca/snac/trade/service/TradeProgressServiceImpl.java
  src/main/java/com/ureca/snac/trade/service/interfaces/TradeInitiationService.java
  src/main/java/com/ureca/snac/trade/service/interfaces/TradeProgressService.java
Labels: bug, enhancement

#85 [feat,reafactor] 토스 api 응답 및 결제취소 자산내역 응답
  src/main/java/com/ureca/snac/asset/dto/AssetHistoryResponse.java
  src/main/java/com/ureca/snac/asset/entity/SourceDomain.java
  src/main/java/com/ureca/snac/asset/repository/AssetHistoryRepository.java
  src/main/java/com/ureca/snac/asset/service/AssetChangedEventFactory.java
  src/main/java/com/ureca/snac/asset/service/AssetHistoryService.java
  src/main/java/com/ureca/snac/asset/service/AssetHistoryServiceImpl.java
  src/main/java/com/ureca/snac/common/BaseCode.java
  src/main/java/com/ureca/snac/dev/service/DevToolServiceImpl.java
  src/main/java/com/ureca/snac/dev/support/DevDataSupport.java
  src/main/java/com/ureca/snac/infra/TossErrorCode.java
  src/main/java/com/ureca/snac/infra/TossPaymentsErrorHandler.java
  src/main/java/com/ureca/snac/infra/config/TossPaymentProperties.java
  src/main/java/com/ureca/snac/money/controller/MoneyRechargeController.java
  src/main/java/com/ureca/snac/money/controller/MoneyRechargeSwagger.java
  src/main/java/com/ureca/snac/money/dto/MoneyRechargePreparedResponse.java
  src/main/java/com/ureca/snac/money/dto/MoneyRechargeResponse.java
  src/main/java/com/ureca/snac/money/dto/MoneyRechargeSuccessResponse.java
  src/main/java/com/ureca/snac/money/repository/MoneyRechargeRepository.java
  src/main/java/com/ureca/snac/money/service/MoneyService.java
  src/main/java/com/ureca/snac/money/service/MoneyServiceImpl.java
  src/main/java/com/ureca/snac/payment/entity/Payment.java
  src/main/java/com/ureca/snac/payment/exception/AlreadyUsedRechargeCannotCancelException.java
  src/main/java/com/ureca/snac/payment/exception/PaymentPeriodExpiredException.java
  src/main/java/com/ureca/snac/payment/exception/PaymentRedirectException.java
  src/main/java/com/ureca/snac/payment/exception/PaymentRedirectExceptionResolver.java
  src/main/java/com/ureca/snac/payment/exception/TossInvalidApiKeyException.java
  src/main/java/com/ureca/snac/payment/exception/TossInvalidCardInfoException.java
  src/main/java/com/ureca/snac/payment/exception/TossNotEnoughBalanceException.java
  src/main/java/com/ureca/snac/payment/exception/TossPaymentsAPiCallException.java
  src/main/java/com/ureca/snac/payment/mapper/PaymentCancelMapper.java
  src/main/java/com/ureca/snac/payment/service/PaymentInternalService.java
  src/main/java/com/ureca/snac/payment/service/PaymentServiceImpl.java
Labels: enhancement, refactor

#87 [feat] 실시간 매칭 거래 강제 종료 기능 구현
  src/main/java/com/ureca/snac/trade/entity/CancelReason.java
  src/main/java/com/ureca/snac/trade/entity/Trade.java
  src/main/java/com/ureca/snac/trade/entity/TradeType.java
  src/main/java/com/ureca/snac/trade/repository/TradeRepository.java
  src/main/java/com/ureca/snac/trade/service/TradeProgressServiceImpl.java
  src/main/java/com/ureca/snac/trade/service/TradeQueryServiceImpl.java
  src/main/java/com/ureca/snac/trade/service/WebSocketTradeEventListener.java
  src/main/java/com/ureca/snac/trade/service/interfaces/TradeProgressService.java
  src/main/java/com/ureca/snac/trade/service/interfaces/TradeQueryService.java
Labels: enhancement

#88 [feat] 개발용 카드 전체 조회 API 구현
  src/main/java/com/ureca/snac/board/controller/CardController.java
  src/main/java/com/ureca/snac/board/controller/CardControllerSwagger.java
  src/main/java/com/ureca/snac/board/service/CardService.java
  src/main/java/com/ureca/snac/board/service/CardServiceImpl.java
Labels: enhancement

#91 [refactor] 모호한 dto id 수정
  src/main/java/com/ureca/snac/board/dto/CardDto.java
  src/main/java/com/ureca/snac/notification/listener/NotificationListener.java
  src/main/java/com/ureca/snac/notification/service/NotificationServiceImpl.java
  src/main/java/com/ureca/snac/trade/dto/TradeDto.java
  src/main/java/com/ureca/snac/trade/service/TradeCancelServiceImpl.java
  src/main/java/com/ureca/snac/trade/service/WebSocketTradeEventListener.java
  src/main/java/com/ureca/snac/trade/service/interfaces/TradeCancelService.java
Labels: enhancement

#90 [feat] 토스 결제 실패
  src/main/java/com/ureca/snac/common/BaseCode.java
  src/main/java/com/ureca/snac/common/exception/InternalServerException.java
  src/main/java/com/ureca/snac/money/service/MoneyServiceImpl.java
  src/main/java/com/ureca/snac/payment/controller/PaymentController.java
  src/main/java/com/ureca/snac/payment/controller/PaymentSwagger.java
  src/main/java/com/ureca/snac/payment/dto/PaymentFailureRequest.java
  src/main/java/com/ureca/snac/payment/entity/Payment.java
  src/main/java/com/ureca/snac/payment/service/PaymentRecoveryService.java
  src/main/java/com/ureca/snac/payment/service/PaymentRecoveryServiceImpl.java
  src/main/java/com/ureca/snac/payment/service/PaymentService.java
  src/main/java/com/ureca/snac/payment/service/PaymentServiceImpl.java
  src/main/java/com/ureca/snac/wallet/service/WalletServiceImpl.java
  src/test/java/com/ureca/snac/money/service/MoneyServiceImplTest.java
  src/test/java/com/ureca/snac/wallet/service/WalletServiceTest.java
Labels: enhancement

#92 [fix, feat] 실시간 거래시 카드가 삭제되지 않는 문제 및 구매자 필터 삭제 기능 구현
  src/main/java/com/ureca/snac/trade/controller/MatchingController.java
  src/main/java/com/ureca/snac/trade/service/MatchingServiceFacade.java
  src/main/java/com/ureca/snac/trade/service/TradeCancelServiceImpl.java
Labels: bug, enhancement

#94 [feat] 실시간 거래 매칭 예외 케이스 수정
  src/main/java/com/ureca/snac/common/BaseCode.java
  src/main/java/com/ureca/snac/trade/controller/BasicTradeController.java
  src/main/java/com/ureca/snac/trade/repository/TradeRepository.java
  src/main/java/com/ureca/snac/trade/service/MatchingServiceFacade.java
  src/main/java/com/ureca/snac/trade/service/TradeCancelServiceImpl.java
  src/main/java/com/ureca/snac/trade/service/TradeFacade.java
  src/main/java/com/ureca/snac/trade/service/TradeProgressServiceImpl.java
  src/main/java/com/ureca/snac/trade/service/TradeQueryServiceImpl.java
  src/main/java/com/ureca/snac/trade/service/WebSocketTradeEventListener.java
  src/main/java/com/ureca/snac/trade/service/interfaces/TradeProgressService.java
  src/main/java/com/ureca/snac/trade/service/interfaces/TradeQueryService.java
  src/main/java/com/ureca/snac/trade/service/response/TradeIdResponse.java
  src/main/java/com/ureca/snac/trade/service/response/TradeResponse.java
Labels: enhancement

#96 Qi1 117 게시글 생성 조회 수정 삭제 api 개발
  src/main/java/com/ureca/snac/asset/entity/TransactionCategory.java
  src/main/java/com/ureca/snac/board/controller/ArticleController.java
  src/main/java/com/ureca/snac/board/controller/ArticleControllerSwagger.java
  src/main/java/com/ureca/snac/board/controller/request/CreateArticleRequest.java
  src/main/java/com/ureca/snac/board/controller/request/UpdateArticleRequest.java
  src/main/java/com/ureca/snac/board/entity/Article.java
  src/main/java/com/ureca/snac/board/exception/ArticleNotFoundException.java
  src/main/java/com/ureca/snac/board/repository/ArticleRepository.java
  src/main/java/com/ureca/snac/board/repository/ArticleRepositoryCustom.java
  src/main/java/com/ureca/snac/board/repository/ArticleRepositoryImpl.java
  src/main/java/com/ureca/snac/board/service/ArticleService.java
  src/main/java/com/ureca/snac/board/service/ArticleServiceImpl.java
  src/main/java/com/ureca/snac/board/service/response/ArticleResponse.java
  src/main/java/com/ureca/snac/board/service/response/CreateArticleResponse.java
  src/main/java/com/ureca/snac/board/service/response/ListArticleResponse.java
  src/main/java/com/ureca/snac/board/service/response/UpdateArticleResponse.java
  src/main/java/com/ureca/snac/common/BaseCode.java
  src/main/java/com/ureca/snac/common/s3/S3Path.java
  src/main/java/com/ureca/snac/common/s3/S3Uploader.java
  src/main/java/com/ureca/snac/trade/service/TradeInitiationServiceImpl.java
  src/main/resources/application.yml
Labels: bug, enhancement, build

#98 [feat] 카드 생성 시 알림 기능 추가
  src/main/java/com/ureca/snac/trade/service/MatchingServiceFacade.java
Labels: bug

#100 [fix] 카드 생성 후 본인 알림 누락 문제 해결
  src/main/java/com/ureca/snac/trade/service/MatchingServiceFacade.java
Labels: hotfix

#101 [feat] 단골 여부 api
  src/main/java/com/ureca/snac/common/BaseCode.java
  src/main/java/com/ureca/snac/favorite/controller/FavoriteController.java
  src/main/java/com/ureca/snac/favorite/controller/FavoriteSwagger.java
  src/main/java/com/ureca/snac/favorite/dto/FavoriteCheckResponse.java
  src/main/java/com/ureca/snac/favorite/service/FavoriteService.java
  src/main/java/com/ureca/snac/favorite/service/FavoriteServiceImpl.java
  src/main/java/com/ureca/snac/trade/controller/BasicTradeController.java
  src/main/java/com/ureca/snac/trade/controller/BasicTradeControllerSwagger.java
  src/main/java/com/ureca/snac/trade/dto/TradeConfirmResponse.java
  src/main/java/com/ureca/snac/trade/dto/TradeDto.java
  src/main/java/com/ureca/snac/trade/service/MatchingServiceFacade.java
  src/main/java/com/ureca/snac/trade/service/TradeFacade.java
  src/main/java/com/ureca/snac/trade/service/TradeProgressServiceImpl.java
  src/main/java/com/ureca/snac/trade/service/interfaces/TradeProgressService.java
Labels: enhancement

#102 [refactor] 단골 api cursor 및 slice 적용
  src/main/java/com/ureca/snac/favorite/controller/FavoriteController.java
  src/main/java/com/ureca/snac/favorite/controller/FavoriteSwagger.java
  src/main/java/com/ureca/snac/favorite/dto/FavoriteListRequest.java
  src/main/java/com/ureca/snac/favorite/repository/FavoriteRepository.java
  src/main/java/com/ureca/snac/favorite/repository/FavoriteRepositoryCustom.java
  src/main/java/com/ureca/snac/favorite/repository/FavoriteRepositoryCustomImpl.java
  src/main/java/com/ureca/snac/favorite/service/FavoriteService.java
  src/main/java/com/ureca/snac/favorite/service/FavoriteServiceImpl.java
Labels: refactor

#99 [feat] 거래 관련 관리자 중재 요청 및 처리
  src/main/java/com/ureca/snac/board/entity/constants/SellStatus.java
  src/main/java/com/ureca/snac/common/BaseCode.java
  src/main/java/com/ureca/snac/trade/controller/AttachmentController.java
  src/main/java/com/ureca/snac/trade/controller/DisputeAdminController.java
  src/main/java/com/ureca/snac/trade/controller/DisputeController.java
  src/main/java/com/ureca/snac/trade/dto/dispute/DisputeAnswerRequest.java
  src/main/java/com/ureca/snac/trade/dto/dispute/DisputeCreateRequest.java
  src/main/java/com/ureca/snac/trade/dto/dispute/DisputeDetailResponse.java
  src/main/java/com/ureca/snac/trade/entity/AuthorType.java
  src/main/java/com/ureca/snac/trade/entity/Dispute.java
  src/main/java/com/ureca/snac/trade/entity/DisputeAttachment.java
  src/main/java/com/ureca/snac/trade/entity/DisputeStatus.java
  src/main/java/com/ureca/snac/trade/entity/DisputeType.java
  src/main/java/com/ureca/snac/trade/entity/Trade.java
  src/main/java/com/ureca/snac/trade/exception/DisputeAdminPermissionDeniedException.java
  src/main/java/com/ureca/snac/trade/exception/DisputeCommentPermissionDeniedException.java
  src/main/java/com/ureca/snac/trade/exception/DisputeNotFoundException.java
  src/main/java/com/ureca/snac/trade/exception/DisputePermissionDeniedException.java
  src/main/java/com/ureca/snac/trade/exception/TradeSendPermissionDeniedException.java
  src/main/java/com/ureca/snac/trade/repository/DisputeAttachmentRepository.java
  src/main/java/com/ureca/snac/trade/repository/DisputeRepository.java
  src/main/java/com/ureca/snac/trade/repository/TradeCancelRepository.java
  src/main/java/com/ureca/snac/trade/repository/TradeRepository.java
  src/main/java/com/ureca/snac/trade/scheduler/TradeAutoProcessor.java
  src/main/java/com/ureca/snac/trade/service/DisputeAdminServiceImpl.java
  src/main/java/com/ureca/snac/trade/service/DisputeServiceImpl.java
  src/main/java/com/ureca/snac/trade/service/TradeCancelServiceImpl.java
  src/main/java/com/ureca/snac/trade/service/interfaces/DisputeAdminService.java
  src/main/java/com/ureca/snac/trade/service/interfaces/DisputeService.java
Labels: enhancement

#103 [feat] 본인이 작성한 구매글 및 판매글 조회 API 추가
  src/main/java/com/ureca/snac/board/controller/CardController.java
  src/main/java/com/ureca/snac/board/controller/CardControllerSwagger.java
  src/main/java/com/ureca/snac/board/repository/CardRepositoryCustom.java
  src/main/java/com/ureca/snac/board/repository/CardRepositoryImpl.java
  src/main/java/com/ureca/snac/board/service/CardService.java
  src/main/java/com/ureca/snac/board/service/CardServiceImpl.java
Labels: enhancement

#104 [feat] 어드민 신고 관련 api 추가 구성
  src/main/java/com/ureca/snac/trade/controller/DisputeAdminController.java
  src/main/java/com/ureca/snac/trade/controller/DisputeController.java
  src/main/java/com/ureca/snac/trade/dto/DisputeSearchCond.java
  src/main/java/com/ureca/snac/trade/repository/DisputeRepository.java
  src/main/java/com/ureca/snac/trade/repository/DisputeRepositoryCustom.java
  src/main/java/com/ureca/snac/trade/repository/DisputeRepositoryImpl.java
  src/main/java/com/ureca/snac/trade/service/DisputeAdminServiceImpl.java
  src/main/java/com/ureca/snac/trade/service/interfaces/DisputeAdminService.java
Labels: enhancement

#106 [refactor] tradeSupport 관련 코드 정리
  src/main/java/com/ureca/snac/trade/scheduler/TradeAutoProcessor.java
  src/main/java/com/ureca/snac/trade/service/DisputeAdminServiceImpl.java
  src/main/java/com/ureca/snac/trade/service/DisputeServiceImpl.java
  src/main/java/com/ureca/snac/trade/service/TradeCancelServiceImpl.java
  src/main/java/com/ureca/snac/trade/service/TradeInitiationServiceImpl.java
  src/main/java/com/ureca/snac/trade/service/TradeProgressServiceImpl.java
  src/main/java/com/ureca/snac/trade/service/TradeQueryServiceImpl.java
  src/main/java/com/ureca/snac/trade/support/TradeSupport.java
Labels: refactor

#108 Hotfix : add nickname field re deploy
  src/main/java/com/ureca/snac/auth/service/JoinServiceImpl.java
  src/main/java/com/ureca/snac/mypage/service/MyPageServiceImpl.java
Labels: hotfix

#111 [refactor] trade initiation service
  src/main/java/com/ureca/snac/board/entity/Card.java
  src/main/java/com/ureca/snac/trade/entity/Trade.java
  src/main/java/com/ureca/snac/trade/service/TradeInitiationServiceImpl.java
Labels: enhancement

#110 refactor: SocialProvider 통합 및 소셜 로그인/연동 로직 리팩토링
  src/main/java/com/ureca/snac/auth/exception/UnsupportedSocialProviderException.java
  src/main/java/com/ureca/snac/auth/oauth2/SocialProvider.java
  src/main/java/com/ureca/snac/auth/repository/AuthRepository.java
  src/main/java/com/ureca/snac/auth/service/CustomOAuth2UserService.java
  src/main/java/com/ureca/snac/auth/service/JoinServiceImpl.java
  src/main/java/com/ureca/snac/auth/service/SocialLoginServiceImpl.java
  src/main/java/com/ureca/snac/auth/service/unlink/GoogleUnlinkServiceImpl.java
  src/main/java/com/ureca/snac/auth/service/unlink/KakaoUnlinkServiceImpl.java
  src/main/java/com/ureca/snac/auth/service/unlink/NaverUnlinkServiceImpl.java
  src/main/java/com/ureca/snac/common/BaseCode.java
  src/main/java/com/ureca/snac/member/Member.java
  src/main/java/com/ureca/snac/mypage/dto/MyPageResponse.java
Labels: refactor

#113 [refactor] trade progress service
  src/main/java/com/ureca/snac/board/entity/Card.java
  src/main/java/com/ureca/snac/board/service/CardServiceImpl.java
  src/main/java/com/ureca/snac/trade/entity/Trade.java
  src/main/java/com/ureca/snac/trade/service/TradeProgressServiceImpl.java
  src/main/java/com/ureca/snac/trade/service/interfaces/TradeProgressService.java
Labels: refactor

#114 fix: 게시글 제목이 누락되는 문제 해결
  src/main/java/com/ureca/snac/board/service/response/ArticleResponse.java
Labels: hotfix

#115 refactor: MemberRepository 패키지 구조 재구성 및 인증 로직을 member 패키지로 이동
  src/main/java/com/ureca/snac/asset/service/AssetHistoryServiceImpl.java
  src/main/java/com/ureca/snac/auth/oauth2/CustomAuthorizationRequestResolver.java
  src/main/java/com/ureca/snac/auth/repository/AuthRepository.java
  src/main/java/com/ureca/snac/auth/service/JoinService.java
  src/main/java/com/ureca/snac/board/service/ArticleServiceImpl.java
  src/main/java/com/ureca/snac/board/service/CardServiceImpl.java
  src/main/java/com/ureca/snac/dev/support/DevDataSupport.java
  src/main/java/com/ureca/snac/favorite/service/FavoriteServiceImpl.java
  src/main/java/com/ureca/snac/finance/service/AccountServiceImpl.java
  src/main/java/com/ureca/snac/member/Member.java
  src/main/java/com/ureca/snac/member/controller/JoinController.java
  src/main/java/com/ureca/snac/member/controller/JoinControllerSwagger.java
  src/main/java/com/ureca/snac/member/dto/request/JoinRequest.java
  src/main/java/com/ureca/snac/member/exception/EmailDuplicateException.java
  src/main/java/com/ureca/snac/member/exception/NicknameDuplicateException.java
  src/main/java/com/ureca/snac/member/repository/MemberRepository.java
  src/main/java/com/ureca/snac/member/service/JoinService.java
  src/main/java/com/ureca/snac/member/service/JoinServiceImpl.java
  src/main/java/com/ureca/snac/member/service/MemberServiceImpl.java
  src/main/java/com/ureca/snac/money/service/MoneyServiceImpl.java
  src/main/java/com/ureca/snac/mypage/service/MyPageServiceImpl.java
  src/main/java/com/ureca/snac/notification/service/NotificationServiceImpl.java
  src/main/java/com/ureca/snac/payment/service/PaymentServiceImpl.java
  src/main/java/com/ureca/snac/trade/scheduler/TradeAutoProcessor.java
  src/main/java/com/ureca/snac/trade/service/AttachmentServiceImpl.java
  src/main/java/com/ureca/snac/trade/service/DisputeAdminServiceImpl.java
  src/main/java/com/ureca/snac/trade/service/DisputeServiceImpl.java
  src/main/java/com/ureca/snac/trade/service/PenaltyServiceImpl.java
  src/main/java/com/ureca/snac/trade/service/TradeCancelServiceImpl.java
  src/main/java/com/ureca/snac/trade/service/TradeInitiationServiceImpl.java
  src/main/java/com/ureca/snac/trade/service/TradeProgressServiceImpl.java
  src/main/java/com/ureca/snac/trade/service/TradeQueryServiceImpl.java
  src/main/java/com/ureca/snac/wallet/listener/WalletEventListener.java
  src/test/java/com/ureca/snac/money/service/MoneyServiceImplTest.java
Labels: refactor

#116 [feat, fix] scheduling lock
  build.gradle
  src/main/java/com/ureca/snac/config/ShedLockConfig.java
  src/main/java/com/ureca/snac/trade/scheduler/TradeStatisticsScheduler.java
  src/main/java/com/ureca/snac/trade/service/response/TradeResponse.java
  src/main/resources/application.yml
Labels: bug, enhancement, hotfix

#117 [feat] retrieve members and posts count
  src/main/java/com/ureca/snac/board/controller/ArticleController.java
  src/main/java/com/ureca/snac/board/controller/ArticleControllerSwagger.java
  src/main/java/com/ureca/snac/board/repository/ArticleRepository.java
  src/main/java/com/ureca/snac/board/service/ArticleService.java
  src/main/java/com/ureca/snac/board/service/ArticleServiceImpl.java
  src/main/java/com/ureca/snac/board/service/response/CountArticleResponse.java
  src/main/java/com/ureca/snac/common/BaseCode.java
  src/main/java/com/ureca/snac/member/controller/MemberController.java
  src/main/java/com/ureca/snac/member/controller/MemberControllerSwagger.java
  src/main/java/com/ureca/snac/member/dto/response/CountMemberResponse.java
  src/main/java/com/ureca/snac/member/repository/MemberRepository.java
  src/main/java/com/ureca/snac/member/service/MemberService.java
  src/main/java/com/ureca/snac/member/service/MemberServiceImpl.java
Labels: enhancement

#120 [feat] 실시간 매칭 거래 소요 시간 통계 기능
  src/main/java/com/ureca/snac/common/BaseCode.java
  src/main/java/com/ureca/snac/trade/controller/TradeDurationStatisticController.java
  src/main/java/com/ureca/snac/trade/controller/TradeDurationStatisticControllerSwagger.java
  src/main/java/com/ureca/snac/trade/entity/TradeDurationStatistic.java
  src/main/java/com/ureca/snac/trade/exception/TradeDurationStatisticNotFoundException.java
  src/main/java/com/ureca/snac/trade/repository/TradeDurationStatisticRepository.java
  src/main/java/com/ureca/snac/trade/repository/TradeRepository.java
  src/main/java/com/ureca/snac/trade/scheduler/TradeDurationScheduler.java
  src/main/java/com/ureca/snac/trade/service/TradeDurationStatisticServiceImpl.java
  src/main/java/com/ureca/snac/trade/service/interfaces/TradeDurationStatisticService.java
  src/main/java/com/ureca/snac/trade/service/response/TradeDurationStatisticResponse.java
Labels: enhancement

#121 [feat] 동일 계정의 소켓 다중 연결 방지 로직 추가
  src/main/java/com/ureca/snac/common/RedisKeyConstants.java
  src/main/java/com/ureca/snac/config/WebConfigRabbitMQ.java
  src/main/java/com/ureca/snac/trade/service/WebSocketTradeEventListener.java
Labels: enhancement

#125 feat: 아직 판매자를 찾지않은 구매글(카드)는 즉시 삭제 가능하도록 변경
  src/main/java/com/ureca/snac/trade/service/TradeCancelServiceImpl.java
Labels: enhancement

#126 [feat] dev 비밀통로 API 구현
  src/main/java/com/ureca/snac/dev/controller/DevToolController.java
  src/main/java/com/ureca/snac/dev/infra/FakePaymentGatewayAdapter.java
  src/main/java/com/ureca/snac/dev/service/DevToolServiceImpl.java
  src/main/java/com/ureca/snac/dev/support/DevDataSupport.java
  src/main/java/com/ureca/snac/infra/TossPaymentsAdapter.java
Labels: enhancement, refactor

#127 [feat] 취소 사유기능 수정, 거래 내역 조회 시 취소 요청 상태 조회 추가
  src/main/java/com/ureca/snac/trade/repository/TradeCancelRepository.java
  src/main/java/com/ureca/snac/trade/service/TradeCancelServiceImpl.java
  src/main/java/com/ureca/snac/trade/service/TradeQueryServiceImpl.java
  src/main/java/com/ureca/snac/trade/service/response/TradeResponse.java
Labels: enhancement
