Repository 2025-Ureca-Snac/snac-server, pull requests merged in 2025-08, with the labels that each got.

#130 refactor: CORS 외부화 및 SecurityConfig 정리, JWT 토큰 생성 중앙화, 소셜 언링크 예외 명확화 및 불필요 코드 정리
  src/main/java/com/ureca/snac/auth/config/CorsConfig.java
  src/main/java/com/ureca/snac/auth/config/CorsProperties.java
  src/main/java/com/ureca/snac/auth/config/SecurityConfig.java
  src/main/java/com/ureca/snac/auth/exception/SocialUnlinkException.java
  src/main/java/com/ureca/snac/auth/exception/SocialUnlinkFailedException.java
  src/main/java/com/ureca/snac/auth/filter/LoginFilter.java
  src/main/java/com/ureca/snac/auth/oauth2/CustomOAuth2FailHandler.java
  src/main/java/com/ureca/snac/auth/oauth2/CustomOAuth2SuccessHandler.java
  src/main/java/com/ureca/snac/auth/service/ReissueServiceImpl.java
  src/main/java/com/ureca/snac/auth/service/SocialLoginServiceImpl.java
  src/main/java/com/ureca/snac/auth/service/unlink/GoogleUnlinkServiceImpl.java
  src/main/java/com/ureca/snac/auth/service/unlink/NaverUnlinkServiceImpl.java
  src/main/java/com/ureca/snac/auth/util/JWTUtil.java
  src/main/java/com/ureca/snac/member/controller/MemberController.java
  src/main/java/com/ureca/snac/member/controller/MemberControllerSwagger.java
  src/main/java/com/ureca/snac/member/dto/request/EmailRequest.java
  src/main/java/com/ureca/snac/member/dto/request/PhoneRequest.java
  src/main/java/com/ureca/snac/member/exception/InvalidCurrentMemberInfoException.java
  src/main/java/com/ureca/snac/member/exception/InvalidCurrentPasswordException.java
  src/main/java/com/ureca/snac/member/service/MemberServiceImpl.java
  src/main/resources/application.yml
Labels: enhancement, refactor

#133 [feat] 스케줄러 서버 프로파일 분리
  src/main/java/com/ureca/snac/config/RabbitMQConfig.java
  src/main/java/com/ureca/snac/config/WebConfigRabbitMQ.java
  src/main/java/com/ureca/snac/notification/listener/NotificationListener.java
  src/main/java/com/ureca/snac/notification/service/NotificationServiceImpl.java
  src/main/java/com/ureca/snac/trade/service/WebSocketTradeEventListener.java
Labels: build

#134 hotfix: 개발을 위해 jwt 토큰 시간 임시로 대폭 늘리고, 닉네임 변경 가능 시간도 마찬가지로 대폭 줄임
  src/main/java/com/ureca/snac/member/entity/Member.java
  src/main/resources/application.yml
Labels: hotfix

#135 [feat] 신고 알림 WebSocket 리스너 추가
  src/main/java/com/ureca/snac/notification/listener/NotificationListener.java
  src/main/java/com/ureca/snac/trade/service/MatchingServiceFacade.java
Labels: bug, enhancement

#138 [hotfix] 카드 및 단골 수정
  src/main/java/com/ureca/snac/board/controller/CardController.java
  src/main/java/com/ureca/snac/board/controller/CardControllerSwagger.java
  src/main/java/com/ureca/snac/board/repository/CardRepositoryCustom.java
  src/main/java/com/ureca/snac/board/repository/CardRepositoryImpl.java
  src/main/java/com/ureca/snac/board/service/CardService.java
  src/main/java/com/ureca/snac/board/service/CardServiceImpl.java
  src/main/java/com/ureca/snac/board/service/response/CardResponse.java
  src/main/java/com/ureca/snac/favorite/repository/FavoriteRepository.java
  src/main/java/com/ureca/snac/trade/controller/BasicTradeController.java
  src/main/java/com/ureca/snac/trade/controller/BasicTradeControllerSwagger.java
  src/main/java/com/ureca/snac/trade/dto/TradeConfirmResponse.java
  src/main/java/com/ureca/snac/trade/service/TradeFacade.java
  src/main/java/com/ureca/snac/trade/service/TradeQueryServiceImpl.java
  src/main/java/com/ureca/snac/trade/service/response/TradeResponse.java
Labels: enhancement, refactor, hotfix

#141 [refactor] 거래 로직에서 불필요한 락 제거
  src/main/java/com/ureca/snac/board/repository/CardRepository.java
  src/main/java/com/ureca/snac/board/service/CardServiceImpl.java
  src/main/java/com/ureca/snac/trade/repository/TradeRepository.java
  src/main/java/com/ureca/snac/trade/service/TradeInitiationServiceImpl.java
  src/main/java/com/ureca/snac/trade/service/TradeProgressServiceImpl.java
  src/main/java/com/ureca/snac/trade/service/WebSocketTradeEventListener.java
Labels: refactor

#142 [feat] 이미지 업로드 및 조회 관련 수정
  src/main/java/com/ureca/snac/common/BaseCode.java
  src/main/java/com/ureca/snac/trade/controller/AttachmentController.java
  src/main/java/com/ureca/snac/trade/controller/DisputeAdminController.java
  src/main/java/com/ureca/snac/trade/controller/DisputeController.java
  src/main/java/com/ureca/snac/trade/service/DisputeServiceImpl.java
Labels: enhancement

#143 [feat] ratingScore 필드 추가
  src/main/java/com/ureca/snac/trade/dto/TradeDto.java
  src/main/java/com/ureca/snac/trade/entity/CancelReason.java
Labels: enhancement

#144 [feat] 신고(문의) 사용자 api 스웨거 작성, 카드캔슬처리 대신 카드삭제 처리
  src/main/java/com/ureca/snac/trade/controller/DisputeController.java
  src/main/java/com/ureca/snac/trade/controller/DisputeControllerSwagger.java
  src/main/java/com/ureca/snac/trade/service/TradeCancelServiceImpl.java
Labels: documentation

#148 [fix] 불필요한 카드 조회 제거
  src/main/java/com/ureca/snac/trade/support/TradeMessageBuilder.java
Labels: bug

#149 [feat] 신고(문의) 관리 기능 스웨거 작성, 관리자 기능 수정 및 dispute 카테고리 필드추가
  src/main/java/com/ureca/snac/trade/controller/DisputeAdminController.java
  src/main/java/com/ureca/snac/trade/controller/DisputeAdminControllerSwagger.java
  src/main/java/com/ureca/snac/trade/dto/DisputeSearchCond.java
  src/main/java/com/ureca/snac/trade/dto/dispute/DisputeDetailResponse.java
  src/main/java/com/ureca/snac/trade/dto/dispute/MyDisputeListItemDto.java
  src/main/java/com/ureca/snac/trade/entity/Dispute.java
  src/main/java/com/ureca/snac/trade/entity/DisputeAttachment.java
  src/main/java/com/ureca/snac/trade/entity/DisputeCategory.java
  src/main/java/com/ureca/snac/trade/entity/DisputeStatus.java
  src/main/java/com/ureca/snac/trade/entity/DisputeType.java
  src/main/java/com/ureca/snac/trade/repository/DisputeRepositoryImpl.java
  src/main/java/com/ureca/snac/trade/service/DisputeAdminServiceImpl.java
  src/main/java/com/ureca/snac/trade/service/DisputeServiceImpl.java
  src/main/java/com/ureca/snac/trade/service/interfaces/DisputeAdminService.java
Labels: enhancement

#152 [hotfix] Profile -> Primary 및 Qualifier 사용으로 해결
  src/main/java/com/ureca/snac/dev/controller/DevToolController.java
  src/main/java/com/ureca/snac/dev/infra/FakePaymentGatewayAdapter.java
  src/main/java/com/ureca/snac/dev/service/DevToolServiceImpl.java
  src/main/java/com/ureca/snac/infra/TossPaymentsAdapter.java
Labels: hotfix

#150 feat: 판매자의 데이터 전송 사진을 멀티모달 을 통한 ocr 검증 및 검증 실패 시 사용자에게 피드백
  build.gradle
  src/main/java/com/ureca/snac/auth/dto/response/ImageValidationResult.java
  src/main/java/com/ureca/snac/auth/exception/lmm/ImageValidationBusinessException.java
  src/main/java/com/ureca/snac/auth/exception/lmm/ImageValidationLlmException.java
  src/main/java/com/ureca/snac/auth/exception/lmm/ImageValidationResponseParseException.java
  src/main/java/com/ureca/snac/auth/service/lmm/LlmImageValidationClient.java
  src/main/java/com/ureca/snac/auth/service/lmm/TradeImageValidationService.java
  src/main/java/com/ureca/snac/auth/util/ImageValidator.java
  src/main/java/com/ureca/snac/auth/util/PromptLoader.java
  src/main/java/com/ureca/snac/common/BaseCode.java
  src/main/java/com/ureca/snac/config/ImageValidationConfig.java
  src/main/java/com/ureca/snac/trade/controller/BasicTradeController.java
  src/main/resources/application.yml
  src/main/resources/prompt/imageValidationPrompt.txt
Labels: enhancement

#153 [feat] dispute 카테고리 별 타입 별 통계 기능 추가, 거래 조회 시 신고정보 불러오기
  src/main/java/com/ureca/snac/common/BaseCode.java
  src/main/java/com/ureca/snac/trade/controller/DisputeAdminController.java
  src/main/java/com/ureca/snac/trade/controller/DisputeAdminControllerSwagger.java
  src/main/java/com/ureca/snac/trade/dto/dispute/DisputeStatisticsResponse.java
  src/main/java/com/ureca/snac/trade/repository/DisputeRepository.java
  src/main/java/com/ureca/snac/trade/repository/TradeCancelRepository.java
  src/main/java/com/ureca/snac/trade/service/DisputeAdminServiceImpl.java
  src/main/java/com/ureca/snac/trade/service/TradeQueryServiceImpl.java
  src/main/java/com/ureca/snac/trade/service/interfaces/DisputeAdminService.java
Labels: enhancement

#158 [chore] SMS 거래 리스너 제거
  src/main/java/com/ureca/snac/auth/listener/EmailListenerServiceImpl.java
  src/main/java/com/ureca/snac/auth/listener/SmsListenerServiceImpl.java
Labels: bug

#159 feat: 실시간 매칭 판매자 데이터 전송 사진 lmm 통한 ocr 검증
  src/main/java/com/ureca/snac/trade/controller/MatchingControllerMVC.java
  src/main/resources/prompt/imageValidationPrompt.txt
Labels: documentation, enhancement

#160 feat: 일반거래, 판매자 매칭 전 거래취소 되지 않던 문제 수정
  src/main/java/com/ureca/snac/trade/support/TradeMessageBuilder.java
Labels: enhancement

#161 [feat] 어드민 신고 조회 시 닉네임 함께 내려주기
  src/main/java/com/ureca/snac/trade/dto/TradeDto.java
  src/main/java/com/ureca/snac/trade/dto/dispute/DisputeDetailResponse.java
  src/main/java/com/ureca/snac/trade/service/DisputeAdminServiceImpl.java
  src/main/java/com/ureca/snac/trade/service/DisputeServiceImpl.java
Labels: enhancement

#162 [test] money, payment, infra(Toss API)
  src/main/resources/application.yml
  src/test/java/com/ureca/snac/infra/TossPaymentsAdapterTest.java
  src/test/java/com/ureca/snac/money/domain/MoneyRechargeTest.java
  src/test/java/com/ureca/snac/money/service/MoneyDepositorTest.java
  src/test/java/com/ureca/snac/money/service/MoneyServiceImplTest.java
  src/test/java/com/ureca/snac/payment/domain/PaymentTest.java
  src/test/java/com/ureca/snac/payment/mapper/PaymentCancelMapperTest.java
  src/test/java/com/ureca/snac/payment/service/PaymentInternalServiceTest.java
  src/test/java/com/ureca/snac/payment/service/PaymentRecoveryServiceImplTest.java
  src/test/java/com/ureca/snac/payment/service/PaymentServiceImplTest.java
  src/test/java/com/ureca/snac/support/TestFixture.java
Labels: documentation, enhancement, test

#165 [feat] 판매자가 구매자 취소요청 기각 후 판매자 취소요청 가능하게 수정
  src/main/java/com/ureca/snac/trade/entity/TradeCancel.java
  src/main/java/com/ureca/snac/trade/service/DisputeAdminServiceImpl.java
  src/main/java/com/ureca/snac/trade/service/TradeCancelServiceImpl.java
Labels: bug

#166 [fix] 취소시 문자가 안오는 문제 해결
  src/main/java/com/ureca/snac/trade/support/TradeMessageBuilder.java
Labels: bug

#167 [hotfix] @Profile
  src/main/java/com/ureca/snac/asset/service/AssetHistoryEventListener.java
  src/main/java/com/ureca/snac/member/service/MemberJoinEventListener.java
Labels: hotfix

#168 chore: JWTFilter 로그 제거.
  src/main/java/com/ureca/snac/auth/filter/JWTFilter.java
Labels: chore

#169 [feat] 신고조회 시 거래 정보가 내려오지 않던 오류 수정
  src/main/java/com/ureca/snac/trade/controller/DisputeAdminController.java
  src/main/java/com/ureca/snac/trade/dto/dispute/DisputeDetailResponse.java
  src/main/java/com/ureca/snac/trade/service/DisputeAdminServiceImpl.java
  src/main/java/com/ureca/snac/trade/service/DisputeServiceImpl.java
  src/main/java/com/ureca/snac/trade/service/interfaces/DisputeAdminService.java
Labels: enhancement
